categories = [
    "person",
    "cat",
    "bird",
    "banana",
    "firehydrant",
    "tree",
    "bus",
    "building"
]

category_palette = {
    "person": "salmon",
    "cat": "orange",
    "bird": "gold",
    "banana": "dodgerBlue",
    "firehydrant": "lightsteelblue",
    "tree": "lightseagreen",
    "bus": "limegreen",
    "building": "darkgreen"
}

rois = [
    'Primary_Visual',
    'Early_Visual',
    'Dorsal_Stream_Visual',
    'Ventral_Stream_Visual',
    'MT__Complex_and_Neighboring_Visual_Areas',
    'Somatosensory_and_Motor',
    'Paracentral_Lobular_and_Mid_Cingulate',
    'Premotor',
    'Posterior_Opercular',
    'Early_Auditory',
    'Auditory_Association',
    'Insular_and_Frontal_Opercular',
    'Medial_Temporal',
    'Lateral_Temporal',
    'Temporo_Parieto_Occipital_Junction',
    'Superior_Parietal',
    'Inferior_Parietal',
    'Posterior_Cingulate',
    'Anterior_Cingulate_and_Medial_Prefrontal',
    'Orbital_and_Polar_Frontal',
    'Inferior_Frontal',
    'Dorsolateral_Prefrontal'
]
rois_groups = {
    'Visual': 'Primary_Visual',
    'Visual': 'Early_Visual',
    'Visual': 'Dorsal_Stream_Visual',
    'Visual': 'Ventral_Stream_Visual',
    'Visual': 'MT__Complex_and_Neighboring_Visual_Areas',
    'Somatosensory and motor': 'Somatosensory_and_Motor',
    'Somatosensory and motor': 'Paracentral_Lobular_and_Mid_Cingulate',
    'Somatosensory and motor': 'Premotor',
    'Somatosensory and motor':'Posterior_Opercular',
    'Auditory': 'Early_Auditory',
    'Auditory': 'Auditory_Association',
    'Auditory': 'Insular_and_Frontal_Opercular',
    'Temporal': 'Medial_Temporal',
    'Temporal': 'Lateral_Temporal',
    'Posterior': 'Temporo_Parieto_Occipital_Junction',
    'Posterior': 'Superior_Parietal',
    'Posterior': 'Inferior_Parietal',
    'Posterior': 'Posterior_Cingulate',
    'Anterior': 'Anterior_Cingulate_and_Medial_Prefrontal',
    'Anterior': 'Orbital_and_Polar_Frontal',
    'Anterior': 'Inferior_Frontal',
    'Anterior': 'Dorsolateral_Prefrontal'
}

images = [
    "control_person1",
    "control_person2",
    "control_person3",
    "control_person4",
    "control_person5",
    "control_person6",
    "control_person7",
    "control_person8",
    "control_person9",
    "control_person10",
    "control_cat1",
    "control_cat2",
    "control_cat3",
    "control_cat4",
    "control_cat5",
    "control_cat6",
    "control_cat7",
    "control_cat8",
    "control_cat9",
    "control_cat10",
    "control_bird1",
    "control_bird2",
    "control_bird3",
    "control_bird4",
    "control_bird5",
    "control_bird6",
    "control_bird7",
    "control_bird8",
    "control_bird9",
    "control_bird10",
    "control_banana1",
    "control_banana2",
    "control_banana3",
    "control_banana4",
    "control_banana5",
    "control_banana6",
    "control_banana7",
    "control_banana8",
    "control_banana9",
    "control_banana10",
    "control_firehydrant1",
    "control_firehydrant2",
    "control_firehydrant3",
    "control_firehydrant4",
    "control_firehydrant5",
    "control_firehydrant6",
    "control_firehydrant7",
    "control_firehydrant8",
    "control_firehydrant9",
    "control_firehydrant10",
    "control_tree1",
    "control_tree2",
    "control_tree3",
    "control_tree4",
    "control_tree5",
    "control_tree6",
    "control_tree7",
    "control_tree8",
    "control_tree9",
    "control_tree10",
    "control_bus1",
    "control_bus2",
    "control_bus3",
    "control_bus4",
    "control_bus5",
    "control_bus6",
    "control_bus7",
    "control_bus8",
    "control_bus9",
    "control_bus10",
    "control_building1",
    "control_building2",
    "control_building3",
    "control_building4",
    "control_building5",
    "control_building6",
    "control_building7",
    "control_building8",
    "control_building9",
    "control_building10"
]

conditions = [
    "control_person",
    "clutter_person",
    "deletion_person",
    "occlusion_person",
    "scrambling_person",
    "control_cat",
    "clutter_cat",
    "deletion_cat",
    "occlusion_cat",
    "scrambling_cat",
    "control_bird",
    "clutter_bird",
    "deletion_bird",
    "occlusion_bird",
    "scrambling_bird",
    "control_banana",
    "clutter_banana",
    "deletion_banana",
    "occlusion_banana",
    "scrambling_banana",
    "control_firehydrant",
    "clutter_firehydrant",
    "deletion_firehydrant",
    "occlusion_firehydrant",
    "scrambling_firehydrant",
    "control_tree",
    "clutter_tree",
    "deletion_tree",
    "occlusion_tree",
    "scrambling_tree",
    "control_bus",
    "clutter_bus",
    "deletion_bus",
    "occlusion_bus",
    "scrambling_bus",
    "control_building",
    "clutter_building",
    "deletion_building",
    "occlusion_building",
    "scrambling_building"
]

control_conditions = [
    "control_person",
    "control_cat",
    "control_bird",
    "control_banana",
    "control_firehydrant",
    "control_tree",
    "control_bus",
    "control_building"
]